.gitignore, .gitmodules, .travis.yml, README.md, main.go
Polish the project a little bit by making it more obvious how to generate `bindata.go` and where the data is supposed to come from.
=> Add OpenAPI submodule + bindata/test instructions

server.go, server_test.go
Requires that the user pass in a valid looking `Authorization` header.
stripe-mock will accept any value that looks like a testmode secret key,
and the idea here is to help detect configuration problems before going
live.
=> Validate authorization

param/coercer/coercer.go, param/coercer/coercer_test.go
Implements coercion to booleans along with the existing support for integers.
=> Implement boolean coercion

param/coercer/coercer.go, param/coercer/coercer_test.go
This patch adds logic to the coercer so that if it runs into an array,
it can descend into it and coerce its elements according to the JSON
schema defined in `items`.
I found that I needed this to get stripe-go's test suite running with
respect to setting a subscription's items.
r? @tmaxwell-stripe
=> Descend into arrays while doing parameter coercing

main.go
Adds logic to fall back to the `PORT` environmental variable if one was
not specified with `--port`. This makes deployment more flexible on some
platforms like Heroku.
The precedence is now (in order of most preferred to least):
1. `--port` via command line arguments.
2. `PORT` via environment.
3. Default port (`12111`).
Here it is in action:
$ PORT=12345 $GOPATH/bin/stripe-mock
stripe-mock master
Routing to 115 path(s) and 196 endpoint(s) with 108 validator(s)
Listening on port 12345
Fixes #42.
r? @ob-stripe 
=> Fall back to the `PORT` environmental variable

.travis.yml, Makefile, generator.go, generator/datareplacer/datareplacer.go, generator_test.go, main.go, param/form/form.go, param/nestedtypeassembler/nestedtypeassembler.go, param/nestedtypeassembler/nestedtypeassembler_test.go, param/param.go, param/parser/parser.go, param/parser/parser_test.go, server.go, server_test.go, spec/spec.go, spec/validate.go
Adds golint and fixes the places that it didn't like. This is a no-op
functionally speaking -- the changes are largely around naming and
comments.
=> Activate golint for stripe-mock

.travis.yml
Recently the team moved (promoted?) this repository. Update the path to
the new location.
cc @remi-stripe
=> Update get path for Golint

generator.go, generator_test.go
Here we extend the ID replacement infrastructure to generate new IDs
from "create" endpoints. For example:
$  curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: Bearer sk_test_123" http://localhost:2345/v1/charges | jq '.id'
"ch_CNT2UVXcbLq0Jt5"
$  curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: Bearer sk_test_123" http://localhost:2345/v1/charges | jq '.id'
"ch_CNT2bb9wsZpgsxT"
With the idea being that much like you get with the Stripe API, new
objects have unique IDs every time.
I ported the same algorithm we use for token generation internally so
that IDs are made up of a prefix (determined from the source fixture), a
time portion, and a random portion. This means that they order in a
mostly ascending way over time …
=> Generates new random primary IDs from "create" endpoints

server.go, server_test.go
Handles all special characters in path parameters that are defined in
RFC3986 instead of just the couple that we'd special cased before, along
with `+` which represents a space.
After matching a patch, we now also run all parameters through
`url.QueryUnescape` to decode `%`-encoded bytes and convert `+`s back to
spaces.
Fixes #157.
r? @mickjermsurawong-stripe
=> Handle more special characters and spaces in path parameters

main.go, server.go, server_test.go
Occasionally an API library or other client might do some path appending
that's slightly off and end up with an extra slash in their target.
`//v1/charges` for example.
While the Stripe API will happily accept this, stripe-mock currently
won't because Go intercepts the doubled slashes fairly high up in the
stack and responds with a 301 to a normalized URL (e.g. `/v1/charges`).
Go's default behavior is probably desirable most of the time, but given
that the Stripe API takes doubled slashes, in this case it makes more
sense to accept them as well. This patch introduces a wrapping handler
that deduplicates slashes on incoming requests, thereby allowing a
request with doubled slashes to succeed normally.
Fixes #170.
r? @ob-stripe Mind taking a look at this one? Thanks!
cc …
=> Deduplicate slashes in incoming paths

bindata.go
=> Update the OpenAPI specification and bundled data

goreleaser.yml
r? @ob-stripe 
cc @brandur-stripe
=> Add go generate hook to GoReleaser

.travis.yml
r? @ob-stripe 
cc @brandur-stripe 
Login to Docker in Travis, otherwise GoReleaser can't publish the image.
(Sorry for the PR spam...)
=> Login to Docker

Makefile
r? @richardm-stripe
This was renamed to `stripe/stripe-mock`, so updating locally to be consistent.
=> Update local Docker image name.

.github/workflows/release.yml
Do the same thing we do in openapi repo and reuse our app.
=> Use GH App for releasing

.github/workflows/tag.yml
So stripe-mock can be released hands-free.
=> Add a workflow to auto-increment the tag

.github/workflows/tag.yml
Use github-token for the token parameter.
=> Fix the token parameter name

.github/workflows/ci.yml, .github/workflows/release.yml, go.mod
There are some strange build errors in https://github.com/stripe/stripe-mock/pull/364
=> Update to go 1.19

goreleaser.yml
Mirrors changes in https://github.com/stripe/homebrew-stripe-mock/pull/8
=> Migrate to the new service brew syntax

embedded/embedded.go, embedded/openapi/fixtures3.beta.json, main.go, spec/spec.go
To test beta APIs.
Binary size goes up from 16 to 20MB.
=> Support beta fixtures

.github/workflows/release.yml, goreleaser.yml
=> Add fix goreleaser config and add release notifications

.github/workflows/release.yml
Just enough to get features we need (`service` annotation) but not trigger other issues.
=> update go releaser

server/server_test.go, spec/spec.go
Fixes loading of embedded specs.
=> Ignore x-stripeError custom annotation

.github/workflows/tag.yml
Similar to https://github.com/stripe/stripe-php/pull/1624
=> Use GITHUB_OUTPUT instead of deprecated ::set-output

spec/spec.go
=> Add deprecated field to supported fields
