stripe/stripe-mock

- server.go
- server_test.go
Sets a special `Stripelocal-Version` response header that will allow
library test suites to judge whether they need a newer version of
stripelocal than the one that's currently running.
> Set special `Stripelocal-Version` response header

- README.md
- goreleaser.yml
- main.go
Port 6065 should have been relatively uncontentious, but just to try and
keep collisions to an absolute mininum, I picked an unassigned port from
this list [1] maintained by the IANA.
[1] https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=120
> Change default port to 12111

- README.md
- generator.go
- generator_test.go
- goreleaser.yml
- main.go
- main_test.go
- param/coercer/coercer.go
- param/coercer/coercer_test.go
- server.go
- server_test.go
- vendor/vendor.json
One final rename before we moved this over to the official GitHub
organization.
> Rename "stripelocal" to "stripe-mock"

- server.go
- server_test.go
The real Stripe API allows basic authentication so lets allow it from stripe-mock as well.
> Allow HTTP basic authentication in addition to bearer

- generator.go
- generator_test.go
- main_test.go
- server_test.go
Previously running concurrency operations against the generator would
result in a panic because it was actually taking maps that it found and
fixtures and mutating them, resulting in concurrent reads and writes.
This patch introduces a fix that copies fixtures that are found in the
decoded set so that each Goroutine is working with a local copy. It also
introduces testing to protect against regressions.
Fixes #10.
> Fix concurrent generator use

- main_test.go
- server.go
- server_test.go
This is just a minor ergonomic improvement so that when making requests from the console, output is more readable.
> Pretty print responses when request is from cURL

- param/coercer/coercer.go
- param/coercer/coercer_test.go
Supports coercion on the JSON schema "number" type like we do already for booleans and integers.
> Support coercion on the "number" type

- param/coercer/coercer.go
- param/coercer/coercer_test.go
- server.go
This is unusual for normal "Rack-style" form encoding, but at Stripe on
some endpoints we allow maps that are indexed with integers to be
changed to arrays in the backend. So for example this:
myarr[0]=foo
Would be interpreted in the API as:
["foo"]
The purpose of this is to be able to use arbitrary indexing to update
only certain items, so this also works:
myarr[3]=foo
Becomes:
[nil, nil, nil "foo"]
You can find an example of this in the `items` parameter on create
subscription.
Here we augment the coercer to detect if the target type is `array` and
then try to coerce a map to a slice as long as all its indexes were
strings that looked like integers.
I've added a test suite, but have also verified that this fixes a
failing test in my stripe-go PR that's targeting stripe-mock.
r? …
> Coerce integer-indexed maps to slices

- generator.go
- main.go
- mapstr.go
- mapstr_test.go
As shown in #22, when we try to unmarshal fixtures from a YAML file, we
end up with a crash in the generator due to a type mismatch.
This turns out to be because of [1]. Because YAML technically supports
boolean keys, the YAML library unmarshals to maps in a way to handle
them (`map[interface{}]interface{}`), even if it's not suitable for most
users (the issue strongly suggests that a lot of people would like
`map[string]interface{}`).
Here we work around the problem by post-processing fixtures that we've
loaded via YAML by recursing through and changing all instances of
`map[interface{}]interface{}` to `map[string]interface{}`. I've added a
few basic tests, but also tested that the call reported in #22 now works
as expected.
Fixes #22.
[1] https://github.com/go-yaml/yaml/issues/139
r? …
> Fix decoded maps when unmarshaling fixtures from a YAML file

- LICENSE
Add a `LICENSE` file to the project which will put `stripe-mock` under
MIT license. This is copied from some of our other open source projects
like stripe-go and stripe-ruby.
Fixes #33.
> License stripe-mock under MIT

- server.go
- server_test.go
This lets stripe-mock return API errors as a JSON payload instead of just the error message.
This fixes https://github.com/stripe/stripe-mock/issues/31 and lets us use stripe-mock better in stripe-python tests for https://github.com/stripe/stripe-python/pull/367
It also ensures that `Request-Id` is properly returned as a header on all requests except the authentication error ones.
> Define a StripeError struct and use this on all API errors

- main.go
I've found it a bit confusing, during stripe-mock version changes, to know what version I'm running. I discovered that I can run `stripe-mock --version` to see what version I have, but it'd be nice if I never had to do that. This (maybe contentious) change will make stripe-mock emit its version each time it runs.
r? @stripe/api-libraries
> Always print the stripe-mock version

- .travis.yml
- scripts/docker_push.sh
Pushes the built Docker image to Docker Hub as part of a Travis deploy
step. This allows Docker users to access the image more easily.
There are a few caveats with this implementation:
1. We're only building `master`. If this ends up being something we use,
we should build tagged version images as well.
2. It pushes to `stripemock/stripe-mock` instead of `stripe/stripe-mock`
because we're having a little trouble getting the collaboration
privileges worked out on Docker Hub's Stripe organization right now.
We should change it to `stripe/stripe-mock` when possible.
Fixes #49.
> Push Docker image to Docker Hub

- .dockerignore
- .travis.yml
- Dockerfile
In #50 I was able to successfully push an image to Docker Hub, but quite
a large one -- weighing in at 91 MB, which is pretty heavy for this
small program. It's big because it includes the entire Go build system.
Here we lean out the final image by switching `Dockerfile` to use a
multi-phase build strategy. This creates one image initially based off
of a Go image which is used to build the final release program, then
creates a second image based on the lightweight Alpine Linux and copies
over the release binary.
This has the effect of reducing the final image's size from 91 MB to a
lean 13.7 MB (that's Alpine Linux + `stripe-mock`), which is faster/cheaper 
for users to pull.
A smaller optimization is to add a `.dockerignore` file which prevents
us from having to copy a number of …
> Leaner Docker image through the use of multi-stage builds

- generator_test.go
So I couldn't figure out what exactly changed here, but as reported in
our channel yesterday, `stripe-mock`'s test suite fails on the latest
version of the OpenAPI spec.
The reason is that when generating list resources, we're currently
filling in `url` with the dud string `<test request path>`, and doing so
causes the generated resource to fail to validate because that string is
not in the OpenAPI spec's `enum` set for `url`.
Here we resolve the problem by plumbing through each URL's path from the
ingested OpenAPI spec and sending it onto the generator.
This doesn't quite fix the problems with the latest OpenAPI though —
there's at least one more case of an invalid fixture which I'm trying to
resolve separately.
r? @tmaxwell-stripe
cc @alexander-stripe
> Send valid path to generator while running test suite

- goreleaser.yml
The old link accidentally includes `.com.com`.
Fixes: https://github.com/stripe/homebrew-stripe-mock/issues/3
> Fix link to `stripe-mock` homepage

- generator.go
- generator_test.go
- main_test.go
- server.go
- server_test.go
When requesting a path from `stripe-mock` with an object's primary ID in
the URL:
```
GET /v1/charges/ch_idFromURL
```
Previously, we'd return the ID from the bundled fixtures. This patch
changes the behavior to try and detect when the path contains an
object's primary ID and reflect that back into the respond instead:
```
{
"id": "ch_idFromURL",
}
```
(Previously, this would have been `ch_123` or whatever the fixtures
contained.)
We also tweak things in a few other places for consistency. If we find a
string value in our generated response with the same value as the ID we
replaced, we replace it as well. This allows an embedded resource with
an ID field that references its parent to reference it with a sane ID
(e.g., the `charge` field on a refund that's embedded in a charge's
`refunds` …
> Reflect an object's primary ID from a path back in the response

- generator.go
- generator_test.go
- spec/spec.go
Here we codify a path to generate a synthetic schema for objects that
couldn't be loaded from fixtures. This is useful in a couple situations:
1. Where we're trying to expand on a deep object that never lives at the
top level of the API (see #46).
2. Where we have a schema that doesn't have have fixtures generated for
it yet (e.g., an internal or prerelease one).
Fixes #46.
r? @tmaxwell I hope it's alright, but just to get the groundwork laid for this
one, I did some other refactoring that wasn't reviewed to nicen things up. The
main thing that changed as that the `Generate` family of functions now take a
`GenerateParams` as they're being invoked, which allows us to document things
more easily, and also prettifies the function signatures because they don't
need to take so many arguments.
> If all other options fail, generate synthetic schemas

- spec/spec.go
Previously, we only ever had the boolean use of `AdditionalProperties`,
in that a `false` was used to specify that no additional properties were
allowed.
As of more recent versions of the spec, we're now using the schema
format for it as well, and this causes the YAML parser to error as it
encounters a value that's not compatible with the `bool` that we had
specified before.
This patch changes `AdditionalProperties` to take an `interface{}` so
that either type can be accepted. This won't be workable if we actually
need a value for `AdditionalProperties`, but we're not using this
property at the moment, so it's fine for now.
> Flexible `AdditionalProperties`

- param/coercer/coercer.go
- param/coercer/coercer_test.go
I was running `stripe-ruby`'s test suite against a recent version of the
OpenAPI, and noticed that unfortunately, recent updates have broken it.
In particular, the new tiers feature under plan creation now has a
primitive type nested in an `anyOf`, which is something that we've never
had to handle before:
``` yaml
up_to:
anyOf:
- enum:
- inf
type: string
- type: integer
```
`stripe-ruby` tries to run this against it:
``` ruby
plan = Stripe::Plan.create(
...
tiers: [{ up_to: 100, amount: 1000 }, { up_to: "inf", amount: 2000 }]
)
```
What's supposed to happen is that "100" is coerced to an integer, but it's not
because the integer possibility is nested in an `anyOf` as seen above.
This patch addresses the problem by allowing the coercer to recurse into an
`anyOf` to try coercion. It's able …
> Support primitives in an `anyOf` from the parameters coercer

- generator.go
- generator_test.go
- server.go
- server_test.go
Implement "advanced" path parameter response reflection
Builds on reflecting URL parameters as introduced in #59 to also support
reflecting parameters beyond just the object's primary ID. More
concretely, if we have a path like this:
/application_fees/fee_123/refunds/re_123
Before we'd just reflect the last part in (`re_123`), but here we now
reflect the parent object in as well (`fee_123`).
The one major caveat to this is that currently our query parameters are
not very introspectable in that we don't really know what kind of object
`fee_123` is supposed to be. To that end, we use the name of the
parameter (in this case `fee`) and compare that it against two places
to see if it's likely a referencing this object:
* A fixture's `object` value.
* The name of the key containing an ID value …
> Implement "advanced" path parameter response reflection

- param/form/form.go
- param/form/form_test.go
- param/nestedtypeassembler/nestedtypeassembler.go
- param/nestedtypeassembler/nestedtypeassembler_test.go
- param/param.go
- param/param_test.go
- param/parser/parser.go
- param/parser/parser_test.go
- server.go
- server_test.go
This makes the changes necessary to be able to successfully validate
payloads sent as `multipart/form-data` along with the standard
`application/x-www-form-urlencoded`.
To accomplish this, I ended up splitting the parameter parser into two
separate components:
1. A new "parser" that just splits an incoming string into form
key/value tuples. This is used to parse query strings and body form
data. We prefer it over Go's built-in parser because it returns
an ordered slice instead of an unordered map, which is critical for
correctly parsing incoming arrays and maps.
2. An "assembler" that takes the parser's output and assembles
higher-level data structures from it, including arrays and maps by
using the "Rack-style" conventions in use by the Stripe API.
To parse `multipart/form-data`, we rely …
> Validate `multipart/form-data` + error on mismatched media types

- generator.go
- generator/datareplacer/datareplacer.go
- generator/datareplacer/datareplacer_test.go
- main_test.go
- server.go
- server_test.go
- spec/validate.go
- vendor/github.com/lestrrat/go-jsval/object.go
Here we try to to some additional enrichment on response data by
replacing what we found in fixtures with data that came in from the
request.
The algorithm is quite simple: we walk the decoded request object and
the generated response object, replace any scalars that we see where the
key name is the same, and recurse in when we see two keys with the same
names that are both maps.
In addition, I realized that we are no longer vetting that incorrect
keys are not being passed to stripe-mock, which appears to be a
regression from a change passed some time ago. This patch also adds back
a check on `additionalProperties: false`.
cc @tmaxwell-stripe Any thoughts on this?
> Replace data in response with data from request

- generator/datareplacer/datareplacer.go
Reflect in Go has the concept of a "zero Value" [1] (not be confused with a
type's zero value with a lowercase "v") and asking for Type on one will
panic. I'm not exactly sure under what conditions these are generated,
but they are occasionally, so here we hedge against them.
See also: https://github.com/stripe/stripe-mock/issues/75
Fixes #75.
[1] https://golang.org/pkg/reflect/#Value
> Hedge against the "zero Value"

- server.go
- server_test.go
Behave like the real Stripe API by reflecting an idempotency key that
was sent into stripe-mock back in the response body.
> Reflect `Idempotency-Key` header back in response

- Dockerfile
- README.md
- main.go
- main_test.go
I was a little hasty in adding support for HTTPS before in that when
we're developing with stripe-mock locally, we need to have a setup that
supports both HTTP *and* HTTPS because some libraries will be using one
and some libraries will be using the other.
I've added a number of command line options that allow stripe-mock to be
booted so that it's listening for both HTTP and HTTPS (and HTTP/2)
simultaneously. It's added a little bit of complication, so I've added a
number of checks for incompatible options and more documentation to the
README on how to use them all.
`12111` will remain our default port for HTTP, and `12112` will become
our default port for HTTPS. Libraries that want HTTP will lock to
`12111` by default and those that need HTTPS will lock to `12112`.
See the README for …
> Support simultaneous HTTP and HTTPS

- README.md
We had a report from a user that it's somewhat difficult to figure out
stripe-mock actually does today. Here we add a few new sections to the
README that describe its current state, its limitations, and what we'd
like to implement down the road.
r? @ob-stripe
> Add README sections for current state and future plans

- server.go
stripe-mock currently needs a whitelist of RPC-style names so that it
can differentiate between an RPC endpoint and a subcollection when
deciding whether to include the primary ID from a URL.
Here we add two new ones for `/approve` and `/decline`.
r? @zanker-stripe
cc @remi-stripe
> Whitelist RPC-style actions `/approve` and `/decline`

- generator.go
- generator_test.go
- main_test.go
- server.go
Implements a simple heuristic so that stripe-mock will pick an `anyOf`
branch based off whether the incoming HTTP request method is a `DELETE`
or or not. If it is `DELETE`, we try to pick the deleted form of a
resource, and vice versa.
We're doing this because we'd occasionally run into a place where
stripe-mock was picking a branch based off its naive "pick the first
branch" logic when it was quite obvious that another branch would
overwhelmingly have been preferred. For example, returning a deleted
customer from `GET /v1/customers/:id` because the deleted customer
appeared first in the `anyOf` list.
The heuristic isn't perfect, but it will usually do the right thing.
r? @ob-stripe
> Decide between returning a deleted versus non-deleted from HTTP method

- generator.go
- generator_test.go
stripe-mock has a feature where it reflects data from input parameters
back into the response so that when creating an updating objects, it
produces responses that look more realistic with some of the actual
input values that were sent in.
Unfortunately, we found that this was working a little _too_ well and
being applied to other operations like listing as well. So for example,
if we request a list with a filter of `object=source`, we'd see a
response where the response list object's `object` field was set to
`source` instead of `list` like it should be.
Here we make sure that data replacement only occurs on `POST`
operations and add some tests to verify this behavior.
r? @remi-stripe
cc @dpetrovics-stripe
> Don't replace data on non-`POST` endpoints

- README.md
The previous command forwarded port 12111 (HTTP) on the host machine to port
12112 (HTTPS) inside the container. That would mean you wouldn't be able to hit
the service over HTTP.
This changes the command to use a port range of 12111-12112 on both sides so
both the HTTP and HTTPS port will be available.
> Fix port number specification for Docker command in README

- param/coercer/coercer.go
- param/coercer/coercer_test.go
As described in #95, there's currently a problem with the coercer in
that if it finds an `anyOf`, it assumes that only primitive schema types
like a `boolean` or `integer` will be present in it.
This isn't true -- it somes cases (say `destination` while creating a
charge), it's possible to have an object _or_ a primitive type. In the
case of the object, stripe-mock wouldn't error, but would also not
coerce anything within it, and therefore requests might fail validation.
Here we consider that an object might be found as welll, and implement
code to handle that case.
Fixes #95.
> Coerce values within an object within an `anyOf`

- param/coercer/coercer.go
- param/coercer/coercer_test.go
Remi saw on #97 that I'd renamed a field to `bool_or_int_key` intending
to change a test, but I'd accidentally forgotten to make that subsequent
change, which was to create a higher fidelity test by testing two
primitive type schemas within the same `anyOf`.
Here I made that change, but noticed when I did it that the tests
started to fail. It turned out this is because we were coercing
primitive types overly aggressively. If for example a boolean schema
received an integer like `123`, `strconv.ParseBool` would fail with an
error, but we'd just default to the value `false`.
In this test, it had the effect of the `anyOf` taking the first boolean
branch, even though the value is much better suited to be coerced to an
integer.
Here we relax primitive type coercion. If a value can be parsed …
> Fix test to match naming + less aggressive parameter coercion

- main.go
- main_test.go
Previously the listener tests depended on a hard-coded port that we
hoped was free. Here we change the strategy slightly to ask the OS for a
free port with `:0`.
Unfortunately, that means also changing some code elsewhere because we
were previously relying on `0` to signify an empty argument. We now
change that to `-1` and update code and tests.
> Improve test setup

- main_test.go
- param/param.go
- server.go
- server_test.go
- spec/query.go
- spec/query_test.go
- spec/spec.go
Add support for validating query parameters on `GET` endpoints
(Non-`GET` endpoints always add all their parameters into the request
body schema in OpenAPI, so we don't have to worry about supporting
them.)
A little bit of background: when generating OpenAPI, we use a simplified
logic that puts parameters for `GET` endpoints in as query parameters,
and puts the parameters for all other types of endpoint in as request
body parameters. This is not exactly right because all endpoints will
read either type of parameter, but it makes things look a little more
correct because convention is to always use query strings on `GET`
endpoints (e.g., `GET /v1/charges?limit=3`).
In stripe-mock, I initially skipped over implementing any kind of
validation on query string parameters because they're not as …
> Add support for query parameters on `GET` endpoints

- .travis.yml
- scripts/docker_push.sh
Creates tags in Docker Hub for (1) the `master` branch when it's built,
and (2) for any builds for Git tags.
Fixes #110.
r? @remi-stripe The tagging only happens on master and tag builds so this might
take a little more finagling after I merge it. I cargo culted from someone
else's implementation, but there may still be something that doesn't work quite
right.
> Create tags for Docker Hub releases

- server.go
Okay, we have to get this whitelist eliminated, but here we add our new
"action-style" endpoints for now.
r? @remi-stripe
> Add new "action" methods to ID replacement whitelist

- main.go
Display actual port for listener. This lets you run stripe-mock with `-http[s]-port 0` to automatically get an unused port and have stripe-mock display the actual port(s):
```
❯ ./stripe-mock -http-port 0 -https-port 0
stripe-mock master
Routing to 177 path(s) and 300 endpoint(s) with 300 validator(s)
Listening for HTTP on port: 58504
Listening for HTTPS on port: 58505
```
> Display actual port for listener

- server.go
An upcoming feature called Subscription Schedules have the /release action. stripe-mock has a list of those actions so that we know to replace the resource id with a fixture one instead.
> Add /release to the list of actions that can return a resource

- param/coercer/coercer.go
- param/coercer/coercer_test.go
- Currently stripe-mock doesn't expect array in `anyOf` schema. When it finds non-primitive sub-schema of `anyOf` it recurses using the main `CoerceParams` method. The method is used for top-level coercion, and assumes schema having properties. Because `Items` sub-schema for the array does not have properties, and it will get dropped. The output will remain as integer-indexed map value. For example, invoice update operation in OpenAPI has param for `custom_fields` as follows:
```
custom_fields:
anyOf:
- items:
properties:
// ...
type: object
type: array
- enum:
- ''
type: string
```
and the resulting stripe-mock error is:
```
Request: POST /v1/invoices/in_123
Request data = map[custom_fields:map[0:map[value:val1 name:foo1] 1:map[name:foo2 value:val2]]]
Request validation error: validator …
```
> Handle `anyOf` schema containing array in params coercer

- param/coercer/coercer.go
- param/coercer/coercer_test.go
- This PR handles anyOf schema of integer and enum. The problem is any string input now satisfies Enum string-ness coercion; we don't actually check the specific type of enum (that is done later).
When given numeric string, it naively satisfies the enum as well, and the validator later complains that the numeric string isn't the integer type. The problematic schema is:
```
anyOf:
- enum:
- inf
maxLength: 5000
type: string
- type: integer
```
- This isn't a problem before trying to handle anyOf Array and code structuring in this PR https://github.com/stripe/stripe-mock/pull/141/files because String isn't considered a primitive and always un-coerced, and thus numeric string will be always be considered as coercion candidate. 
- Looking at that PR again, string coercion helps to make …
> Fix handling anyOf enum and number

- main.go
- main_test.go
- server.go
- server_test.go
- spec/spec.go
Adds a new option called `-strict-version-check` that causes stripe-mock
to check that any value passed in an incoming request's `Stripe-Version`
header matches the version specified in the bundled OpenAPI
specification.
This is intended to act as an optionally strengthened expectation which
protects against an unintended drift between a bundled stripe-mock /
OpenAPI and the version being used from an API library. We'll likely
want to enable the option for static libraries like stripe-go and
stripe-dotnet.
r? @ob-stripe
> Add new option `-strict-version-check`

- server.go
This adds new endpoints name that unblock test suites in our client libraries for new resources `PaymentIntent` and `PaymentMethod`.
cc @stripe/api-libraries 
We likely need a better way moving forward as we're committing to more and more "verb" actions though.
> Add new API operations with custom words

- goreleaser.yml
This has the homebrew package author be @stripe-ci instead of @goreleaserbot
> Have the homebrew package commit author be 'stripe-ci'

- bindata.go
- main.go
r? @ob-stripe 
cc @brandur-stripe 
Override file timestamps when using `go-bindata`, so the results are consistent across different systems (file modification times are not preserved by git).
> Override file timestamps

- bindata.go
- main.go
r? @ob-stripe 
cc @brandur-stripe 
It turns out that the file mode can _also_ vary between environments. In this PR we're forcing them to 444, i.e. `r--r--r--`, i.e. read-only for everyone.
> Override file mode

- goreleaser.yml
r? @ob-stripe 
cc @brandur-stripe 
😭 So I think the Docker image I'm building locally works because:
> The cgo tool is enabled by default for native builds on systems where it is expected to work. It is disabled by default when cross-compiling.
(https://golang.org/cmd/cgo/)
So when building the Linux executable from my macOS laptop, it's cross-compiling so cgo is disabled. However, when Travis builds the Linux executable from a Linux container, it's a native build and cgo is enabled, resulting in an executable that doesn't work in the Alpine container.
> Disable cgo in GoReleaser

- .editorconfig
- .gitattributes
- .vscode/extensions.json
- .vscode/settings.json
A bunch of various improvements for devs working on stripe-mock:
- `.editorconfig` file for consistent style
- VS Code settings for graphical editor heathens like me
- mark `bindata.go` as generated so GitHub hides the diff by default
> Various development improvements

- server.go
Allow requests to be made to stripe-mock with the restricted access key
prefix (`rk_`) as well as the standard secret key prefix (`sk_`).
Fixes #199.
r? @ob-stripe
> Allow `rk_` keys in addition to `sk_`

- server.go
Previous commit didn't add this file properly.
> Add /preview endpoint for CreditNote

- main.go
- main_test.go
Adds two new command line options that allow users to specify which IPs
they'd like stripe-mock to listen on.
Currently, only `-http-port` and `-https-port` are supported, which pass
an empty string to Go's `Listen` function, which causes stripe-mock to
listen on every available unicast and anycast address on the system [1].
This is fine for most users, but some want a little more control.
The glut of options available for binding to addresses is starting to
get a little out of control, so I've added a comment to the effect that
we're keeping existing options for compatibility, but that we should
consider deprecating `-http-port`, `-https-port`, `-port`, and `-unix`
to simplify the equation somewhat. Maybe at the same time we should
switch to Unix style flags too. (And maybe this will …
> Add `-http-addr` and `-https-addr` options to listen on alternate IPs

- Makefile
Adding 2 commands to the Makefile:
- docker_build: runs the appropriate `docker build` command and tags the resulting image with the current commit hash as well as updating the `latest` tag
- docker_run: runs the appropriate `docker run` command with the default ports configured
If this PR is unnecessary, please feel free to close it. =)
> Adding convenience commands to Makefile for building and running docker image locally

- generator.go
- generator/datareplacer/datareplacer.go
- generator/datareplacer/datareplacer_test.go
Previously, the data replacer worked by taking input request and output 
response data, and replacing values if the types matched up. This generally
worked, but would result in some inappropriate replacements for more
complex data types like arrays, as seen in [1].
In this patch we upgrade the replacement strategy so that we perform 
replacements if the type of incoming request data matches what we expected
in the response based on the OpenAPI schema. This allows us, for example,
to not only check that a type is an array, but also what sort of elements
that array is supposed to contain, even if the value from our fixtures is
an empty array (which is often the case).
Fixes #210.
r? @ob-stripe
---
[1] https://github.com/stripe/stripe-mock/issues/210
> Rebuild data replacement strategy to use input from OpenAPI schema

- server.go
Add support for `/submit` as a custom endpoint so that stripe-mock properly handles extracting the id from the URL. This endpoint is specific to the Issuing Dispute API which is going to GA on Thursday
r? @brandur-stripe @richardm-stripe 
> Add support for new /submit endpoint to stripe-mock

- server.go
Updates the list of suffixes for API methods with primary IDs to include `/accept`. This is in preparation of Quotes, which will have `/v1/quotes/qt_<id>/accept`. This ensure stripe-mock extracts and returns the primary ID for these calls.
> Include /accept in URL paths which have a primary ID.

- main_test.go
- server.go
- server_test.go
Update stripe-mock to a) stop failing whenever it encounters an endpoint which has `application/pdf` instead of `application/json` and b) write a raw string for these endpoints instead of marshalling it into a JSON string (eg. `"a"` -> `"\"a\""`)
> Update stripe-mock to return raw strings for application/pdf endpoints.

- generator.go
- generator_test.go
r? @richardm-stripe 
Adds support for generating a `search_result` object with a single data element, rather than generating an empty result. This is similar to `list` behavior. As `search_result` has a slightly different schema, opted for duplicating the logic but happy to merge it in together.
This will need the updated OpenAPI spec before we can merge.
> Add support for search_result objects.

- goreleaser.yml
Releases are broken: https://github.com/stripe/stripe-mock/actions/runs/1322583063
It's complaining about "inconsistent vendoring". This PR adds one of the flags that `go generate` recommends to squelch the error.
For a little context, Golang doesn't have a great story for "devDependencies" -- i.e. packages you depend on that you only use for your build/release process, but don't want to add to your go.mod because you don't want to introduce indirect dependencies to the packages that depend on your package. What we do to handle this is just to manually install the dependencies before running `go generate` in our goreleaser script:
```yaml
before:
hooks:
- go get -u honnef.co/go/tools/cmd/staticcheck@latest
- go install github.com/go-bindata/go-bindata/...@latest
- go generate
```
> goreleaser: fix "staticcheck" vendoring

- goreleaser.yml
When installing `stripe-mock` on Apple Silicon devices using homebrew, the following error occurs:
```
brew install stripe/stripe-mock/stripe-mock
==> Tapping stripe/stripe-mock
Cloning into '/opt/homebrew/Library/Taps/stripe/homebrew-stripe-mock'...
remote: Enumerating objects: 457, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 457 (delta 12), reused 0 (delta 0), pack-reused 418
Receiving objects: 100% (457/457), 62.71 KiB | 917.00 KiB/s, done.
Resolving deltas: 100% (148/148), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/stripe/homebrew-stripe-mock/stripe-mock.rb
formulae require at least a URL
Error: Cannot tap stripe/stripe-mock: invalid syntax in tap!
```
This change attempts to update the brew formula …
> Add support for Apple Silicon / ARM64

- README.md
r? @kamil-stripe @richardm-stripe 
Updates the README to use the correct docker image name.
Fixes https://github.com/stripe/stripe-mock/issues/299
> Fix docker image name in README.

- server/server.go
- server/server_test.go
Sets an appropriate `Content-Type` response header, mirroring our production API. Currently stripe-mock always returns JSON or PDF (it doesn't support the Files API).
Fixes https://github.com/stripe/stripe-mock/issues/312
> fix: Set Content-Type on responses.

- .github/workflows/tag.yml
Running `git` requires the repo to be checked out.
> Checkout the repository before tagging

- .github/workflows/tag.yml
The default `fetch-depth: 1` doesn't bring down all the tags. We need existing tags to determine the new tag.
> Fetch history when cloning the repo for tagging

- spec/spec.go
- spec/spec_test.go
https://github.com/stripe/stripe-mock/pull/337 had a subtle bug where additional properties were not loaded correctly from the OpenAPI JSON file. Fix it and add more tests.
> Fix additionalProperties loading

- server/generator.go
- server/generator_test.go
We were using only the first segment of fixture ID for random ID generation. `sub_sched_123` was turned into `sub_123456` in the process.
> Handle ID prefixes with underscores

- README.md
cc @stripe/api-libraries 
We've had several github issues open for years requesting more sophisticated testing features for stripe-mock, like statefulness. This used to be something that we intended to add, but just never prioritized, but in more recent years our thinking about the proper scope of this project has changed internally, and it's time we communicate this to users and set more realistic expectations.
This PR changes the README to reflect how we think about this project and it's scope. After it is merged, I plan on updating/closing all our stale issues on this repository so they reflect the current project direction.
> Edit the README to reflect narrower scope

- goreleaser.yml
Reverts stripe/stripe-mock#380
This causes a [CI error](https://github.com/stripe/stripe-mock/actions/runs/4346863543/jobs/7593453209) during release, reverting to investigate
> Revert "Add support for multi-platform Docker images"

- .github/workflows/release.yml
- goreleaser.yml
Noticed #392. In order to build the amd64 image it's necessary to install qemu and buildx.
Validated on my fork: https://github.com/ewdurbin/stripe-mock/actions/runs/4364861761/jobs/7632707111#step:6:102
> Fix multi arch release

- server/generator.go
- server/generator_test.go
Now that pattern can be a real regex we can't just copy it when generating a `url` value. 
I tried to make id generation logic more clever but the way ID replacement currently works makes the change quite involved.
> Replace pattern placeholders when generating urls

- Dockerfile
- embedded/openapi/fixtures3.json
Native binary loaded into docker images doesn't work in case of Mac. Hence changed docker to build and create the docker image.
```
docker build -t ""stripe/stripe-mock":latest" -t ""stripe/stripe-mock":ec39425c3ff31dca6993447238e34f243250acc6" .
[+] Building 10.4s (13/13) FINISHED
=> [internal] load build definition from Dockerfile                                                                                                                         0.0s
=> => transferring dockerfile: 378B                                                                                                                                         0.0s
=> [internal] load .dockerignore …
```
> fix(Docker): Macos docker failure

- goreleaser.dockerfile
- goreleaser.yml
Turns out #430 isn't compatible with goreleaser, which seems obvious in retrospect. I found [goreleaser docs](https://goreleaser.com/errors/docker-build) that suggest
> If you still want your users to be able to docker build without an extra step, you can have a Dockerfile just for GoReleaser, for example, a goreleaser.dockefile.
so, this PR is that.
> Separate dockerfile for goreleaser

- goreleaser.yml
In https://github.com/stripe/stripe-mock/pull/432 the setting was added to the wrong place.
Confirmed that the correct dockerfile is picked up by running `goreleaser release --skip-publish --clean --verbose --skip-validate`
> Fix dockerfile setting

- README.md
Starting in Go 1.17, installing executables with go get is deprecated. go install should be used instead.
This closes #436
> Update installation command to use "go install" instead of "go get"(deprecated) in README.md file

- server/generator.go
- server/generator_test.go
The issue in https://github.com/stripe/stripe-mock/issues/445 is caused by [a crash](https://github.com/stripe/stripe-mock/blob/1f05c0034db7407b9d77724f532f508ead46a1fb/server/generator.go#L339) when you try to expand a nullable attribute:
```
$ stripe-mock
stripe-mock 0.159.0
Routing to 306 path(s) and 453 endpoint(s) with 453 validator(s)
Listening for HTTP at address: [::]:12111
Listening for HTTPS at address: [::]:12112
Request: GET /v1/invoices/in_1NhTSDJ7Bu9fw2TI7tY1f5zD
Request data = map[expand:[account_tax_ids]]
2023/08/25 15:27:12 http: panic serving 127.0.0.1:53788: Responding to GET /v1/invoices/in_1NhTSDJ7Bu9fw2TI7tY1f5zD:
Dereferencing '#/components/schemas/invoice':
Using fixture 'invoice':
In property 'account_tax_ids' of object:
We were asked to expand a key, but our …
```
> Generate synthetic fixtures for nullable types when expansions are requested

- server/generator.go
Fixes https://github.com/stripe/stripe-mock/issues/447
Validated locally:
```
// Before
curl -vvvv -g "http://localhost:12111/v1/customers/cus_123" -u sk_test_123:
...
{
...
"invoice_settings": {
"custom_fields": null,
"default_payment_method": "", <-- Causes ValueError by setting to an empty string
"footer": null,
"rendering_options": null
},
...
}
```
```
// After
curl -vvvv -g "http://localhost:12111/v1/customers/cus_123" -u sk_test_123:
...
{
...
"invoice_settings": {
"custom_fields": null,
"default_payment_method": null,
"footer": null,
"rendering_options": null
},
...
}
```
> Stricter check for generating synthetic fixtures

- README.md
Travis hasn't been in use in this repo since 2021 (e7223678959a07d025da2a743def234d2263e973).
> Replace broken Travis CI status badge in README

- .github/workflows/ci.yml
- .github/workflows/release.yml
- go.mod
CI has been failing on the automated PR with the below error:
Based on https://github.com/dominikh/go-tools/issues/1592, the static analysis tool we are using needs a min of 1.22.1 version of go
> Update Go version to 1.22.1

- Makefile
- embedded/openapi/fixtures3.json
When working on https://github.com/stripe/openapi/pull/157, it was convenient to be able to specify the branch name to pull from in the update step.  This let me test the changes end to end before merging the PRs.  This PR makes this configurability official.
- adds OPENAPI_BRANCH Makefile variable that update-openapi-spec can use to select a branch to pull from.  defaults to master.
> Make branch name configurable in update-openapi-spec
